basic:
  instance: default
  data-path-prefix: '/var/cache/server-autoconfig/data_'
  debug-level: 0

upstream:
  git-addr: https://my-git-server/serverconfig.git
  git-pull-branch: main
  git-backup-branch: backup-router

services:

  dnsmasq:
    restart-before: 'ifdown eth1'
    restart-after: 'bash -c "/var/test.sh"'
    restart-method: systemd-reload
    systemd-units:
      - dnsmasq.service
    files:
      - /router/dnsmasq/dnsmasq.conf:/etc/dnsmasq/dnsmasq.conf
  
  my_service:
    restart-method: command
    restart-command: 'systemctl restart smb.service && systemctl reload nmb.service'
    files:
      - /router/samba/samba.conf:/etc/samba/samba.conf
      - /router/samba/custom.conf:/var/spool/samba/custom.conf
