config:
  instance: 1a2b
  data-path-prefix: '/var/cache/server-autoconfig/data_'
  debug-level: 0

upstream:
  git-addr: https://git.example.com/conf.git
  git-branch: master

services:
  dnsmasq:
    reload-method: systemd-reload
    systemd-units:
      - dnsmasq.service
    files:
      - /router/dnsmasq/dnsmasq.conf:/etc/dnsmasq/dnsmasq.conf
  my_service:
    reload-method: command
    reload-command: 'pkill my_service && my_service -d'
    files:
      - /file-server/smb.conf:/etc/samba/smb.conf